include_guard(DIRECTORY)

if(NOT WIN32)
    string(ASCII 27 Esc)
    set(ColourReset "${Esc}[0;m")
    set(ColourBold  "${Esc}[0;1m")
    set(Red         "${Esc}[0;31m")
    set(Green       "${Esc}[0;32m")
    set(Yellow      "${Esc}[0;33m")
    set(Blue        "${Esc}[0;34m")
    set(Magenta     "${Esc}[0;35m")
    set(Cyan        "${Esc}[0;36m")
    set(White       "${Esc}[0;39m")
    set(BoldRed     "${Esc}[1;31m")
    set(BoldGreen   "${Esc}[1;32m")
    set(BoldYellow  "${Esc}[1;33m")
    set(BoldBlue    "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan    "${Esc}[1;36m")
    set(BoldWhite   "${Esc}[1;38m")
endif()

function(colored_message color message)
    message("${color}${message}${ColourReset}")
endfunction()
